// Blip's model catalog — ported from Handy's registry (src-tauri model.rs).
// `id` values MUST match the Rust registry in src-tauri/src/stt.rs.
// Whisper models run on whisper.cpp (CUDA); the rest run on ONNX Runtime
// (DirectML) via transcribe-rs. Scores are 0..1 (bar fill). Recommended-first.
// Shared by Onboarding.svelte and ModelManager.svelte so card visuals and
// metadata stay consistent.
export const MODELS = [
  {
    id: 'parakeet-tdt-0.6b-v3',
    name: 'Parakeet V3',
    engine: 'Parakeet',
    desc: 'Fast and accurate. Supports 25 European languages.',
    sizeMb: 456,
    langLabel: '25 languages',
    multilang: true,
    translate: false,
    accuracy: 0.8,
    speed: 0.85,
    recommended: true,
  },
  {
    id: 'parakeet-tdt-0.6b-v2',
    name: 'Parakeet V2',
    engine: 'Parakeet',
    desc: 'English only. The best model for English speakers.',
    sizeMb: 451,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.85,
    speed: 0.85,
  },
  {
    id: 'turbo',
    name: 'Whisper Large v3 Turbo',
    engine: 'Whisper',
    desc: 'Large v3 Turbo — balanced accuracy and speed. Multilingual.',
    sizeMb: 1549,
    langLabel: 'Multilingual',
    multilang: true,
    translate: false,
    accuracy: 0.8,
    speed: 0.4,
  },
  {
    id: 'large',
    name: 'Whisper Large v3',
    engine: 'Whisper',
    desc: 'Large v3 (q5_0). Best Whisper accuracy, incl. accents — but slow.',
    sizeMb: 1031,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.85,
    speed: 0.3,
  },
  {
    id: 'medium',
    name: 'Whisper Medium',
    engine: 'Whisper',
    desc: 'Good accuracy, medium speed. Multilingual.',
    sizeMb: 469,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.75,
    speed: 0.6,
  },
  {
    id: 'small',
    name: 'Whisper Small',
    engine: 'Whisper',
    desc: 'Fast and fairly accurate. A great lightweight default.',
    sizeMb: 465,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.6,
    speed: 0.85,
  },
  {
    id: 'canary-1b-v2',
    name: 'Canary 1B v2',
    engine: 'Canary',
    desc: 'Accurate multilingual. 25 European languages. Translates.',
    sizeMb: 691,
    langLabel: '25 languages',
    multilang: true,
    translate: true,
    accuracy: 0.85,
    speed: 0.7,
  },
  {
    id: 'cohere-int8',
    name: 'Cohere',
    engine: 'Cohere',
    desc: 'Large, slower, but very accurate multilingual model.',
    sizeMb: 1708,
    langLabel: '16 languages',
    multilang: true,
    translate: false,
    accuracy: 0.9,
    speed: 0.6,
  },
  {
    id: 'sense-voice-int8',
    name: 'SenseVoice',
    engine: 'SenseVoice',
    desc: 'Very fast. Chinese, English, Japanese, Korean, Cantonese.',
    sizeMb: 152,
    langLabel: '5 languages',
    multilang: true,
    translate: false,
    accuracy: 0.65,
    speed: 0.95,
  },
  {
    id: 'canary-180m-flash',
    name: 'Canary 180M Flash',
    engine: 'Canary',
    desc: 'Very fast. English, German, Spanish, French. Translates.',
    sizeMb: 146,
    langLabel: '4 languages',
    multilang: true,
    translate: true,
    accuracy: 0.75,
    speed: 0.85,
  },
  {
    id: 'gigaam-v3-e2e-ctc',
    name: 'GigaAM v3',
    engine: 'GigaAM',
    desc: 'Russian speech recognition. Fast and accurate.',
    sizeMb: 151,
    langLabel: 'Russian',
    multilang: false,
    translate: false,
    accuracy: 0.85,
    speed: 0.75,
  },
  {
    id: 'breeze-asr',
    name: 'Breeze ASR',
    engine: 'Whisper',
    desc: 'Optimized for Taiwanese Mandarin. Code-switching support.',
    sizeMb: 1030,
    langLabel: 'Multilingual',
    multilang: true,
    translate: false,
    accuracy: 0.85,
    speed: 0.35,
  },
  {
    id: 'moonshine-base',
    name: 'Moonshine Base',
    engine: 'Moonshine',
    desc: 'Very fast, English only. Handles accents well.',
    sizeMb: 55,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.7,
    speed: 0.9,
  },
  {
    id: 'moonshine-medium-streaming-en',
    name: 'Moonshine V2 Medium',
    engine: 'Moonshine',
    desc: 'English only. High quality.',
    sizeMb: 192,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.75,
    speed: 0.8,
  },
  {
    id: 'moonshine-small-streaming-en',
    name: 'Moonshine V2 Small',
    engine: 'Moonshine',
    desc: 'Fast, English only. Good balance of speed and accuracy.',
    sizeMb: 99,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.65,
    speed: 0.9,
  },
  {
    id: 'moonshine-tiny-streaming-en',
    name: 'Moonshine V2 Tiny',
    engine: 'Moonshine',
    desc: 'Ultra-fast, English only.',
    sizeMb: 31,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.55,
    speed: 0.95,
  },
];

export function formatSize(mb) {
  return mb >= 1000 ? `${(mb / 1000).toFixed(1)} GB` : `${mb} MB`;
}
