// Yap's model catalog — ported from Handy's registry (src-tauri model.rs).
// `id` values MUST match the Rust registry in src-tauri/src/stt.rs.
// Whisper models run on whisper.cpp (Vulkan GPU); the rest run on ONNX Runtime
// (DirectML) via transcribe-rs. Shared by Onboarding.svelte and ModelManager.svelte.
//
// `accuracy` / `speed` are 0..1 bar fills, calibrated from REAL benchmarks (not
// guesses): accuracy from English WER on the HuggingFace Open ASR Leaderboard
// (+ model cards/papers for non-leaderboard models, domain-weighted for the
// language specialists), speed from leaderboard RTFx / architecture class
// (non-autoregressive TDT/CTC ≫ Whisper autoregressive). See the benchmark notes
// in memory/yap-release-channels. Keep the ordering consistent if you edit these.
export const MODELS = [
  {
    id: 'parakeet-tdt-0.6b-v3',
    name: 'Parakeet V3',
    engine: 'Parakeet',
    desc: 'Top accuracy and the fastest engine. 25 European languages.',
    sizeMb: 456,
    langLabel: '25 languages',
    multilang: true,
    translate: false,
    accuracy: 0.88,
    speed: 0.96,
    recommended: true,
  },
  {
    id: 'parakeet-tdt-0.6b-v2',
    name: 'Parakeet V2',
    engine: 'Parakeet',
    desc: 'English only — the top pick for English speakers. Extremely fast.',
    sizeMb: 451,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.9,
    speed: 0.97,
  },
  {
    id: 'turbo',
    name: 'Whisper Large v3 Turbo',
    engine: 'Whisper',
    desc: 'Faster than Large v3, slightly less accurate. Multilingual.',
    sizeMb: 1549,
    langLabel: 'Multilingual',
    multilang: true,
    translate: false,
    accuracy: 0.8,
    speed: 0.48,
  },
  {
    id: 'large',
    name: 'Whisper Large v3',
    engine: 'Whisper',
    desc: 'Best Whisper accuracy (q5_0), incl. accents — but slow.',
    sizeMb: 1031,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.81,
    speed: 0.3,
  },
  {
    id: 'medium',
    name: 'Whisper Medium',
    engine: 'Whisper',
    desc: 'Good accuracy, medium speed. Multilingual.',
    sizeMb: 469,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.76,
    speed: 0.45,
  },
  {
    id: 'small',
    name: 'Whisper Small',
    engine: 'Whisper',
    desc: 'Lightweight multilingual Whisper. Middling accuracy and speed.',
    sizeMb: 465,
    langLabel: 'Multilingual',
    multilang: true,
    translate: true,
    accuracy: 0.65,
    speed: 0.6,
  },
  {
    id: 'canary-1b-v2',
    name: 'Canary 1B v2',
    engine: 'Canary',
    desc: 'Accurate multilingual. 25 European languages. Translates.',
    sizeMb: 691,
    langLabel: '25 languages',
    multilang: true,
    translate: true,
    accuracy: 0.84,
    speed: 0.72,
  },
  {
    id: 'cohere-int8',
    name: 'Cohere',
    engine: 'Cohere',
    desc: 'Most accurate model — tops the Open ASR Leaderboard. Multilingual.',
    sizeMb: 1708,
    langLabel: '14 languages',
    multilang: true,
    translate: false,
    accuracy: 0.93,
    speed: 0.62,
  },
  {
    id: 'sense-voice-int8',
    name: 'SenseVoice',
    engine: 'SenseVoice',
    desc: 'Very fast, best-in-class for Chinese/Japanese/Korean. Also en, yue.',
    sizeMb: 152,
    langLabel: '5 languages',
    multilang: true,
    translate: false,
    accuracy: 0.72,
    speed: 0.92,
  },
  {
    id: 'canary-180m-flash',
    name: 'Canary 180M Flash',
    engine: 'Canary',
    desc: 'Very fast. English, German, Spanish, French. Translates.',
    sizeMb: 146,
    langLabel: '4 languages',
    multilang: true,
    translate: true,
    accuracy: 0.77,
    speed: 0.9,
  },
  {
    id: 'gigaam-v3-e2e-ctc',
    name: 'GigaAM v3',
    engine: 'GigaAM',
    desc: 'Russian specialist — beats Whisper Large on Russian. Very fast.',
    sizeMb: 151,
    langLabel: 'Russian',
    multilang: false,
    translate: false,
    accuracy: 0.88,
    speed: 0.9,
  },
  {
    id: 'breeze-asr',
    name: 'Breeze ASR',
    engine: 'Whisper',
    desc: 'Taiwanese Mandarin specialist with code-switching. Slow (Whisper-class).',
    sizeMb: 1030,
    langLabel: 'Multilingual',
    multilang: true,
    translate: false,
    accuracy: 0.84,
    speed: 0.28,
  },
  {
    id: 'moonshine-base',
    name: 'Moonshine Base',
    engine: 'Moonshine',
    desc: 'Tiny, very fast English model — great for short voice commands.',
    sizeMb: 55,
    langLabel: 'English only',
    multilang: false,
    translate: false,
    accuracy: 0.6,
    speed: 0.88,
  },
];

export function formatSize(mb) {
  return mb >= 1000 ? `${(mb / 1000).toFixed(1)} GB` : `${mb} MB`;
}
