-- Sign in with your phone: Better Auth's deviceAuthorization plugin (OAuth
-- 2.0 device authorization, RFC 8628; options in src/auth.ts). One row per
-- code Yap asks for. The plugin deletes a row when Yap redeems it, or polls
-- it after a deny or expiry; src/index.ts drops abandoned ones an hour after
-- they expire. Generated by `npm run schema` (auth.cli.ts): the new table only.
create table "deviceCode" ("id" text not null primary key, "deviceCode" text not null, "userCode" text not null, "userId" text, "expiresAt" date not null, "status" text not null, "lastPolledAt" date, "pollingInterval" integer, "clientId" text, "scope" text);

create unique index "deviceCode_deviceCode_uidx" on "deviceCode" ("deviceCode");

create unique index "deviceCode_userCode_uidx" on "deviceCode" ("userCode");
